server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=si1v3r, shuai
            - AddRequestParameter=name, blue
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/inCaseOfFailureUseThis
            - RewritePath=/consumingServiceEndpoint, /backingServiceEndpoint


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
