
spring:
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: dev


server:
  address: 0.0.0.0
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

si1v3r:
  client:
    assess-key: admin01
    secret-key: abcdefgh
